spring:
  application:
    name: api_productos

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:productos}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:vlekUzMExjTxetLSqNKNbmCWldkIMfOt}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
