spring:
  application:
    name: api_productos

  datasource:
    url: jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQL_DATABASE:productos}
    username: ${MYSQLUSER:root}
    password: ${MYSQL_ROOT_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
