spring:
  application:
    name: api_productos
  datasource:
    url: jdbc:mysql://localhost:3306/productos
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
